services:
  portfolio:
    restart: always
    build:
      context: .
    container_name: portfolio
    ports:
      - "3000:3000"
#     networks:
#       - nginx_default
#
# networks:
#   nginx_default:
#     external: true
