name: Hetnzer Deploy on Push

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HETZNER }}
        known_hosts: ${{ secrets.HETZNER_KNOWN_HOSTS }}
    - name: Checkout the Repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.HETZNER }}
        fetch-depth: 0
        ref: master
    - name: Push to Hetzner
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add prod ssh://root@188.245.75.177:/git/portfolio
        git push deployment
